### ISSUE TITLE
TypeError: index 0 has type 'QgsPointXY' but 'QgsPoint' is expected

### ISSUE THREAD

**Issue by merkato** [blazek/lrs#17]
Traceback (most recent call last):
  File "/home/mechanik/.local/share/QGIS/QGIS3/profiles/default/python/plugins/lrs/ui/lrsdockwidget.py", line 636, in generateLrs
    self.lrs.calibrate()
  File "/home/mechanik/.local/share/QGIS/QGIS3/profiles/default/python/plugins/lrs/lrs/lrscalib.py", line 236, in calibrate
    route.calibrate(self.extrapolate)
  File "/home/mechanik/.local/share/QGIS/QGIS3/profiles/default/python/plugins/lrs/lrs/lrscalibroute.py", line 92, in calibrate
    self.buildParts()
  File "/home/mechanik/.local/share/QGIS/QGIS3/profiles/default/python/plugins/lrs/lrs/lrscalibroute.py", line 359, in buildParts
    part = LrsCalibPart(polyline, self.routeId, origins, self.crs, self.measureUnit, self.distanceArea)
  File "/home/mechanik/.local/share/QGIS/QGIS3/profiles/default/python/plugins/lrs/lrs/lrscalibpart.py", line 35, in __init__
    self.setPolyline(polyline)
  File "/home/mechanik/.local/share/QGIS/QGIS3/profiles/default/python/plugins/lrs/lrs/lrscalibpart.py", line 48, in setPolyline
    self.polylineGeo = QgsGeometry.fromPolyline(self.polyline)
TypeError: index 0 has type 'QgsPointXY' but 'QgsPoint' is expected
-----------------------
Wersja Pythona: 3.6.3 (default, Oct  3 2017, 21:45:48) [GCC 7.2.0] 
Wersja QGIS: 2.99.0-Master Master, 5c22e31 
----------------------
LRS version 1.0.0 from official QGIS repository

**Comment by blazek** [comment]
The QGIS API has changed again recently, this is already fixed in master, I have to make new release.

**Comment by blazek** [comment]
I have uploaded new fixed version 1.0.1.
