### ISSUE TITLE
TypeError: unable to convert a QVariant of type 10 to a QMetaType of type 2 

### ISSUE THREAD

**Issue by xorZDrox** [blazek/lrs#27]
Hi Radim,

When install LRS on Qgis  3.2.0-Bonn  bc43194 but also with the previous revision I have this issue:

 TypeError: unable to convert a QVariant of type 10 to a QMetaType of type 2 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 346, in startPlugin
    plugins[packageName].initGui()
  File "/home/geo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/lrs/lrsplugin.py", line 65, in initGui
    self.dockWidget = LrsDockWidget(self.iface.mainWindow(), self.iface)
  File "/home/geo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/lrs/ui/lrsdockwidget.py", line 278, in __init__
    self.resetExportOptions()
  File "/home/geo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/lrs/ui/lrsdockwidget.py", line 1064, in resetExportOptions
    for connection in ExportPostgis.getPostgisConnections():
  File "/home/geo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/lrs/lrs/postgis.py", line 136, in getPostgisConnections
    connection = ExportPostgis.getPostgisConnection(connectionName)
  File "/home/geo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/lrs/lrs/postgis.py", line 117, in getPostgisConnection
    sslmode = settings.value("sslmode", QgsDataSourceUri.SslPrefer, type=int)
TypeError: unable to convert a QVariant of type 10 to a QMetaType of type 2

Thanks

**Comment by merkato** [comment]
Xubuntu 18.04, QGIS3.2, default PostGIS settings. Issue present.

**Comment by blazek** [comment]
Fixed in 3a659f6. It was residue of old direct export to postgis. It will be in 1.0.3.
