### ISSUE TITLE
Error when selecting route: arguments did not match any overloaded call

### ISSUE THREAD

**Issue by simonsouth** [blazek/lrs#28]
Using LRS 1.0.2 with QGIS 3.2.1, after selecting a layer with measures and a route field, trying to select a route from the "Route" dropdown on the "Locate" tab fails with an error message like the following:

```
2018-07-28T06:09:48     WARNING    Traceback (most recent call last):
              File "C:/.../QGIS/QGIS3\profiles\default/python/plugins\lrs\ui\lrsdockwidget.py", line 858, in locateRouteChanged
              self.resetLocateEvent()
              File "C:/.../QGIS/QGIS3\profiles\default/python/plugins\lrs\ui\lrsdockwidget.py", line 875, in resetLocateEvent
              transform = QgsCoordinateTransform(self.lrsLayer.crs, mapSettings.destinationCrs())
             TypeError: QgsCoordinateTransform(): arguments did not match any overloaded call:
              overload 1: too many arguments
              overload 2: not enough arguments
              overload 3: not enough arguments
              overload 4: not enough arguments
              overload 5: argument 1 has unexpected type 'QgsCoordinateReferenceSystem'
```

This appears to be related to [API changes in QGIS 3](https://www.qgis.org/api/api_break.html#qgis_api_break_3_0_QgsCoordinateTransform).

**Comment by blazek** [comment]
I am travelling, i'll look at it within two weeks.

**Comment by blazek** [comment]
Fixed using Simon's pull request. Will be in 1.0.3.
