### ISSUE TITLE
Error calculating measures: arguments did not match any overloaded call

### ISSUE THREAD

**Issue by simonsouth** [blazek/lrs#34]
Using LRS 1.0.2 with QGIS 3.2.1, trying to calculate measures (using the "Measures" tab of the plugin) fails with an error message like the following:

```
2018-07-30T14:52:26     WARNING    Traceback (most recent call last):
              File "C:/.../QGIS/QGIS3\profiles\default/python/plugins\lrs\ui\lrsdockwidget.py", line 1058, in calculateMeasures
              measures.calculate(layer, routeFieldName, measureFieldName, threshold, outputName)
              File "C:/.../QGIS/QGIS3\profiles\default/python/plugins\lrs\lrs\lrsmeasures.py", line 70, in calculate
              transform = QgsCoordinateTransform(layer.crs(), self.lrs.crs)
             TypeError: QgsCoordinateTransform(): arguments did not match any overloaded call:
              overload 1: too many arguments
              overload 2: not enough arguments
              overload 3: not enough arguments
              overload 4: not enough arguments
              overload 5: argument 1 has unexpected type 'QgsCoordinateReferenceSystem'
```

This is similar to issue #28 and also relates to [changes to the QGIS API in version 3](https://www.qgis.org/api/api_break.html#qgis_api_break_3_0_QgsCoordinateTransform).

**Comment by blazek** [comment]
Fixed using Simon's pull request. Will be in 1.0.3.
